config/routes.rb
Rails.application.routes.draw do
  root 'static_notes#home'

  get '/about', to: 'static_notes#about'
  resources :notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  def change
    create_table :pages do |t|
      t.string :title
      t.string :author
      t.text :body

      t.timestamps
    end
  end
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all
  end

  def show
    @note = Note.find(params[:id])
  end

  def new
    @note = Note.new
  end

  def create 
    @note = Note.new(notes_params)
    if @note.save 
      redirect_to notes_path
    else 
      render :new 
    end 
  end 

  def edit 
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
  
    if @note.update(note_params)
      redirect_to note_path
    else
      render :edit
    end
  end

  private 

  def notes_params 
    params.require(:note).permit(:title, :author, :body)
  end 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Notes', notes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StickyNotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<h1>Edit Note</h1>
<%= form_for @note do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/notes/index.html.erb
<h1>Notes</h1>

<p><%= link_to 'New Note', new_note_path %></p>


<% @notes.each do |note| %>
  <h2><%= note.title %></h2>
  <%= link_to 'Show Note', note_path(note) %>
  <%= link_to 'Edit Note', edit_note_path(note) %>
<% end %>

app/views/notes/new.html.erb
<h1>Notes</h1>

<%= form_for @note do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>
  
  <%= f.submit %>
<% end %>

app/views/notes/show.html.erb
<h1>Notes</h1>
<h1><%= @note.title %></h1>
<h2><%= @note.author %></h2> 
<p><%= @note.body %></p>
<%= link_to 'Back', notes_path%>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/new.html.erb
<h1>Pages#new</h1>
<p>Find me in app/views/pages/new.html.erb</p>

app/views/pages/show.html.erb
<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>